### ISSUE TITLE
JWT Credentials for a cosumer

### ISSUE THREAD

**Issue by lvillarino** [therealgambo/kong-php#1]
Hi;

I want to know how I add or delete a JWT credentials (https://getkong.org/plugins/jwt/) for a consumer. 

Thanks

**Comment by therealgambo** [comment]
Because the JWT endpoints are part of a plugin, you currently need to make a "raw" request to kong. Future plans do include a wrapper class to handle this nicely.

Heres a basic example for creating a new JWT credential.
```php
$kong = new Kong();
$consumer = $kong->getConsumer();

$payload = [
'algorithm' => 'HS256',
'secret' => 'mysupersecretkey'
];

$response = $consumer->request('POST', 'consumers/<consumer_id>/jwt', [], $payload);
```

As for deleting, it is the same process of making a raw request.

```
$response = $consumer->request('DELETE', 'consumers/<consumer_id>/jwt/<jwt_id>');
```

**Comment by therealgambo** [comment]
@lvillarino, I've started a basic implementation of this in a new branch `jwt-plugin`. If you want you can try that out, I've still yet to test it and add in some additional methods within the next day or two.

```
$kong = new Kong();
$jwt = $kong->getPluginJwt();

// exposes the current methods
$jwt->createConsumer();
$jwt->create();
$jwt->delete();
$jwt->list();
```

It's worth noting, this will not produce a JWT token, this simply creates the credential in Kong. To create a valid JWT token that you can use, I would recommend using https://github.com/lcobucci/jwt or any other library mentioned on https://jwt.io

**Comment by lvillarino** [comment]
Can you create a method that delete all the credentials? or a rotate method that delete all credentials and create new ones.

Thanks
